[package]
name = "rust-learnings"
version = "0.2.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.11.1"
rayon = "1.5.1"
rand = "0.9.0"
